- name: Patch OS new stuff playbook
  hosts: all
  tasks:
    - name: Patching Red Hat Enterprise Linux
      debug:
        msg: "Patched Red Hat Enterprise Linux. Now at: {{ ansible_distribution_version }}"
